######################################################################
# Automatically generated by qmake (3.0) Thu Jun 5 14:41:36 2014
######################################################################

QT += testlib
TEMPLATE = app
TARGET = tests
INCLUDEPATH += /usr/local/include/ \
              /Users/benedicte/CVGui/

LIBS += -L/usr/local/lib \
     -lopencv_core \
     -lopencv_imgproc \
     -lopencv_features2d\
     -lopencv_highgui


# Input
SOURCES += tests.cpp \
        ../cvutils.cpp \
        ../Chessboard.cpp \
        ../Line.cpp \

HEADERS  += ../Chessboard.h \
    ../Line.h
